<a href="https://colab.research.google.com/github/SOUMEE2000/Machine-Learning-Stash/blob/main/Neural_nets_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Single-Layer-Perceptron**

In [ ]:
import numpy as np
import seaborn as sns

In [ ]:
X= np.array([[1,0,0],[1,0,1],[1,0,1],[0,0,0]])
Y= np.array([[1],[0],[0],[1]])

In [ ]:
X.shape[1]

3

In [ ]:
#### Weights
np.random.seed(10)
weights = np.random.random((3,1))
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [ ]:
weights.shape

(3, 1)

In [ ]:
bias=0.02
sum= np.dot(X,weights) +bias

In [ ]:
#activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [ ]:
predicted_output= sigmoid(sum)
predicted_output

array([[0.68811483],
       [0.8061162 ],
       [0.8061162 ],
       [0.50499983]])

In [ ]:
# cost= out-pred
error = Y - predicted_output
error

array([[ 0.31188517],
       [-0.8061162 ],
       [-0.8061162 ],
       [ 0.49500017]])

In [ ]:
def gradient(x):
  return x * (1-x)

In [ ]:
for i in range(2000):
    sum = 0.02 + np.dot(X,weights)
    predicted_output = sigmoid(sum)
    error = (Y- predicted_output)
    adjustment = error * gradient(predicted_output)   ### gradient descent
    weights += 0.01*np.dot(X.T,adjustment)     # input_samples.T is transpose so that matrix dimension matches
error

array([[ 0.39108414],
       [-0.18807247],
       [-0.18807247],
       [ 0.49500017]])

# **Multi-Layer Perceptron (Using Matrices)**
*For n neurons, 1 hidden layer*

In [30]:
learning_rate = 0.48 #@param {type:"slider", min:0, max:1, step:0.01}
no_of_hidden_neurons = 5 #@param {type:"slider", min:0, max:10, step:1}
epochs = 10 #@param {type:"slider", min:0, max:500, step:10}

In [31]:
import numpy as np
import seaborn as sns

In [32]:

#activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [33]:
def gradient(x):
  return x * (1-x)

In [34]:
def network(input_layer, output_layer, weights1, weights2, learning_rate):
   
   X_input_hidden= np.dot(input_layer, weights1)
   predicted_output_hidden= sigmoid(X_input_hidden)
   
   X_input_output= np.dot(predicted_output_hidden, weights2)
   predicted_output= sigmoid(X_input_output)
     
   error_output= predicted_output - output_layer               ### error at the output layer
   error_hidden= np.dot(error_output,weights2.T)                ### error at the hidden layer
   
   adjustment = error_output * gradient(predicted_output)   ### gradient descent for hidden-output layer
   weights2 -= learning_rate*np.dot(predicted_output_hidden.T,adjustment)          ### weight updation of hidden-output layer.
  
   adjustment = error_hidden * gradient(predicted_output_hidden)   ### gradient descent between input-hidden layer
   weights1 -= learning_rate*np.dot(input_layer.T,adjustment)           ### weight updation between input-hidden layer.
   
   return (weights1, weights2, error_output)
     

In [35]:
def training_network(epochs, inputs, outputs, no_of_hidden_neurons, learning_rate):

  h =no_of_hidden_neurons

  weights1=np.random.random(size=(inputs.shape[1], h))
  weights2= np.random.random(size=(h, outputs.shape[1]))
  for i in range(epochs):
    for j in range(len(inputs)):
      weights1, weights2, error_output = network(np.array([inputs[j]]), np.array([outputs[j]]), weights1, weights2,learning_rate)
    print("For epoch %d error: %.3f " %(i, error_output.mean()))

In [36]:

dataset = np.array([[2.7810836,2.550537003],
	[1.465489372,2.362125076],
	[3.396561688,4.400293529],
	[1.38807019,1.850220317],
	[3.06407232,3.005305973],
	[7.627531214,2.759262235],
	[5.332441248,2.088626775],
	[6.922596716,1.77106367],
	[8.675418651,-0.242068655],
	[7.673756466,3.508563011]])

Y= np.array([[1,0],
             [0,1],
             [1,1],
             [0,1],
             [1,0],
             [1,1],
             [0,1],
             [0,0],
             [1,1],
             [0,1]])


In [37]:
training_network(epochs, dataset, Y, no_of_hidden_neurons, learning_rate)

For epoch 0 error: 0.313 
For epoch 1 error: 0.159 
For epoch 2 error: 0.135 
For epoch 3 error: 0.123 
For epoch 4 error: 0.118 
For epoch 5 error: 0.116 
For epoch 6 error: 0.115 
For epoch 7 error: 0.114 
For epoch 8 error: 0.114 
For epoch 9 error: 0.115 


The error has definitely decreased.

In [38]:
np.array([dataset[0]]).shape

(1, 2)

In [39]:
Y.shape

(10, 2)

# **Multi-Layer Perceptron (Using Matrices)**

*For n neurons, m hidden layers*

In [87]:
learning_rate = 0.22 #@param {type:"slider", min:0, max:1, step:0.01}
epochs = 90 #@param {type:"slider", min:0, max:500, step:10}

In [ ]:
!jupyter nbconvert --to markdown Neural_nets_From_Scratch.ipynb

In [42]:
import numpy as np
import seaborn as sns

In [43]:
#activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [44]:
def gradient(x):
  return x * (1-x)

In [45]:
def network(input_layer, output_layer, weights, learning_rate):

   predicted=[]
   input=input_layer
   for i in weights:
     X_input_hidden= np.dot(input, i)
     predicted_output_hidden= sigmoid(X_input_hidden)
     predicted.append(predicted_output_hidden)
     input= predicted_output_hidden

   error=[]
   error_output = predicted[-1]- output_layer
   error.append(error_output)
   weights.reverse()

   for i in range(len(weights)-1):
     error_hidden= np.dot(error_output,weights[i].T)
     error.insert(0, error_hidden)
     error_output= error_hidden
  
   weights.reverse()
   adjustment = error[0] * gradient(predicted[0])   ### gradient descent between input-hidden layer
   weights[0] -= learning_rate * np.dot(input_layer.T,adjustment)
   for i in range(0,len(weights)-1):
     adjustment = error[i+1] * gradient(predicted[i+1])
     weights[i+1] -= learning_rate * np.dot(predicted[i].T, adjustment)
   
   return (weights, predicted[-1]- output_layer)
     

In [46]:
def training_network(epochs, inputs, outputs, no_of_hidden_neurons, learning_rate):

  h= no_of_hidden_neurons
  weights=[]
  weights.append(np.random.random(size=(inputs.shape[1],h[0])))
  
  for i in range(0,len(no_of_hidden_neurons)-1):
    weights.append(np.random.random(size=(h[i], h[i+1])))
  
  weights.append(np.random.random(size=(h[-1], outputs.shape[1])))
  
  for i in range(epochs):
   for j in range(len(inputs)):
    weights, error_output = network(np.array([inputs[j]]), np.array([outputs[j]]), weights,learning_rate)
   print("For epoch %d error: %.3f " %(i, error_output.mean()))

In [47]:

dataset = np.array([[2.7810836,2.550537003],
	[1.465489372,2.362125076],
	[3.396561688,4.400293529],
	[1.38807019,1.850220317],
	[3.06407232,3.005305973],
	[7.627531214,2.759262235],
	[5.332441248,2.088626775],
	[6.922596716,1.77106367],
	[8.675418651,-0.242068655],
	[7.673756466,3.508563011]])

Y= np.array([[1,0],
             [0,1],
             [1,1],
             [1,0],
             [0,0],
             [0,1],
             [0,1],
             [0,1],
             [1,1],
             [1,0]])

In [48]:
training_network(epochs, dataset, Y, (4,4), learning_rate)

For epoch 0 error: 0.224 
For epoch 1 error: 0.158 
For epoch 2 error: 0.137 
For epoch 3 error: 0.123 
For epoch 4 error: 0.112 
For epoch 5 error: 0.102 
For epoch 6 error: 0.095 
For epoch 7 error: 0.089 
For epoch 8 error: 0.084 
For epoch 9 error: 0.081 
For epoch 10 error: 0.078 
For epoch 11 error: 0.076 
For epoch 12 error: 0.074 
For epoch 13 error: 0.073 
For epoch 14 error: 0.072 
For epoch 15 error: 0.071 
For epoch 16 error: 0.070 
For epoch 17 error: 0.070 
For epoch 18 error: 0.070 
For epoch 19 error: 0.069 
For epoch 20 error: 0.069 
For epoch 21 error: 0.069 
For epoch 22 error: 0.069 
For epoch 23 error: 0.069 
For epoch 24 error: 0.068 
For epoch 25 error: 0.068 
For epoch 26 error: 0.068 
For epoch 27 error: 0.068 
For epoch 28 error: 0.068 
For epoch 29 error: 0.068 
For epoch 30 error: 0.068 
For epoch 31 error: 0.068 
For epoch 32 error: 0.067 
For epoch 33 error: 0.067 
For epoch 34 error: 0.067 
For epoch 35 error: 0.067 
For epoch 36 error: 0.067 
For epoch 3

# **Iris Dataset**

In [ ]:
learning_rate = 0.22 #@param {type:"slider", min:0, max:1, step:0.01}
epoch = 0.22 #@param {type:"slider", min:0, max:500, step:10}


In [49]:
from zipfile import ZipFile
file_name = "/content/archive.zip"
with ZipFile(file_name,'r') as zip:
  zip.extractall()
  print('finish')

finish


In [292]:
import pandas as pd
import numpy as np
dataset= pd.read_csv("Iris.csv", index_col=0)

In [293]:
dataset.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [294]:
# shuffle around
dataset= dataset.sample(frac=1)

In [295]:
dataset["Species"].value_counts()

Iris-virginica     50
Iris-versicolor    50
Iris-setosa        50
Name: Species, dtype: int64

In [296]:
list_spec=[]

for i in dataset["Species"]:
  if i=="Iris-setosa":
    list_spec.append(0)
  elif i=="Iris-versicolor":
    list_spec.append(1)
  elif i== "Iris-virginica":
    list_spec.append(2)

In [ ]:
from numpy import array
from numpy import argmax
from tensorflow.keras.utils import to_categorical
# define example
data = list_spec
data = array(data)

# one hot encode
encoded = to_categorical(data)
print(encoded)

In [298]:
data_feature=dataset.drop("Species", axis=1)

In [299]:
class neural_network():

  def __init__(self):
    self.weights=[]
  
  def network(self, input_layer, output_layer, learning_rate):

    predicted=[]
    input=input_layer
    for i in self.weights:
      X_input_hidden= np.dot(input, i)
      predicted_output_hidden= sigmoid(X_input_hidden)
      predicted.append(predicted_output_hidden)
      input= predicted_output_hidden

    error=[]
    error_output = predicted[-1]- output_layer
    error.append(error_output)
    self.weights.reverse()
    
    for i in self.weights:
      error_hidden= np.dot(error_output,i.T)
      error.insert(0, error_hidden)
      error_output= error_hidden

    self.weights.reverse()
    error = error[1:]
    adjustment = error[0] * gradient(predicted[0])   ### gradient descent between input-hidden layer
    self.weights[0] -= learning_rate * np.dot(input_layer.T,adjustment)

    for i in range(0,len(self.weights)-1):
      adjustment = error[i+1] * gradient(predicted[i+1])
      self.weights[i+1] -= learning_rate * np.dot(predicted[i].T, adjustment)

    return (self.weights, predicted[-1]- output_layer)

  
  
  def training_network(self, epochs, inputs, outputs, no_of_hidden_neurons, learning_rate):
    
    h= no_of_hidden_neurons
    self.weights.append(np.random.random(size=(inputs.shape[1],h[0])))
    
    for i in range(0,len(no_of_hidden_neurons)-1):
      self.weights.append(np.random.random(size=(h[i], h[i+1])))
    self.weights.append(np.random.random(size=(h[-1], outputs.shape[1])))

    for i in range(epochs):
      for j in range(len(inputs)):
        self.weights, error_output = self.network(np.array([inputs[j]]), outputs[j], learning_rate)

      print("For epoch %d error: %.3f " %(i, error_output.mean()))

    
  def predict(self, X_test):
    results=[]
    for j in X_test:
      input=j
      for i in self.weights:
        X_input_hidden= np.dot(input, i)
        predicted_output_hidden= sigmoid(X_input_hidden)
        input= predicted_output_hidden
      results.append(np.argmax(predicted_output_hidden))

    return results

    


In [300]:
print(np.array(y_train[0]))

[0. 0. 1.]


In [301]:
np.array([y_train[0]]).shape

(1, 3)

In [302]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_features = scaler.fit_transform(dataset.drop('Species', axis=1))

In [308]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(scaled_features, list_spec,
                                                    test_size=0.30)
y_train= to_categorical(y_train)

In [309]:
mlp = neural_network()

In [310]:
mlp.training_network(epochs, X_train, y_train, (15,20), learning_rate)

For epoch 0 error: 0.543 
For epoch 1 error: 0.409 
For epoch 2 error: 0.216 
For epoch 3 error: 0.075 
For epoch 4 error: 0.030 
For epoch 5 error: 0.017 
For epoch 6 error: 0.014 
For epoch 7 error: 0.013 
For epoch 8 error: 0.014 
For epoch 9 error: 0.014 
For epoch 10 error: 0.015 
For epoch 11 error: 0.016 
For epoch 12 error: 0.018 
For epoch 13 error: 0.019 
For epoch 14 error: 0.021 
For epoch 15 error: 0.024 
For epoch 16 error: 0.029 
For epoch 17 error: 0.036 
For epoch 18 error: 0.043 
For epoch 19 error: 0.047 
For epoch 20 error: 0.048 
For epoch 21 error: 0.047 
For epoch 22 error: 0.046 
For epoch 23 error: 0.045 
For epoch 24 error: 0.044 
For epoch 25 error: 0.042 
For epoch 26 error: 0.041 
For epoch 27 error: 0.040 
For epoch 28 error: 0.039 
For epoch 29 error: 0.038 
For epoch 30 error: 0.038 
For epoch 31 error: 0.038 
For epoch 32 error: 0.038 
For epoch 33 error: 0.038 
For epoch 34 error: 0.039 
For epoch 35 error: 0.040 
For epoch 36 error: 0.041 
For epoch 3

In [311]:
y_pred = mlp.predict(X_test)

In [312]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9555555555555556